### ISSUE TITLE
Update for Raspberry Pi Model B+

### ISSUE THREAD

**Issue by ul5255** [organix/pijFORTHos#4]
Dale,
here is an update to part of your blinker example. This now works on
Raspberry Pi B+. This model has the LED moved to GPIO pin #47.
Also the logic here is that the LED goes *ON* when you set the pin.
Hope this helps,
Uwe.

16# 20200010 CONSTANT GPFSEL4     \ GPIO function select (pins 40..49)
16# 00E00000 CONSTANT GPIO47_FSEL \ GPIO pin 47 function select mask
16# 00200000 CONSTANT GPIO47_OUT  \ GPIO pin 47 function is output
GPFSEL4 @                         \ read GPIO function selection
GPIO47_FSEL INVERT AND            \ clear function for pin 47
GPIO47_OUT OR                     \ set function to output
GPFSEL4 !                         \ write GPIO function selection

16# 20200020 CONSTANT GPSET1      \ GPIO pin output set (pins 32..53)
16# 2020002C CONSTANT GPCLR1      \ GPIO pin output clear (pins 32..53)
16# 00008000 CONSTANT GPIO47_PIN  \ GPIO pin 47 set/clear
: +gpio47 GPIO47_PIN GPSET1 ! ;   \ set GPIO pin 47
: -gpio47 GPIO47_PIN GPCLR1 ! ;   \ clear GPIO pin 47
: LED_ON +gpio47 ;                \ turn on ACT/OK LED set 47)
: LED_OFF -gpio47 ;               \ turn off ACT/OK LED (clear 47)

**Comment by ginchiest** [comment]
Would someone be willing to vector "emit" to use PI's screen  & "key" to use pi's usb at boot-up?
